### PR TITLE
Fix for Registering a factory for a remote loader doesnt work (issue #15) 

### LINKED ISSUE #15: Registering a factory for a remote loader doesnt work
I want to use a custom remote translation loader.
Sadly there is no documentation on this anywhere on the docs...
I've read the source code and it seems like I could do this:
module.config.php
```php
return [
  'translator' => [
    'remote_translation' => [
        ['type' => MyLoader::class],
    ],
  ],
  'translator_plugins' => [
    'factories' => [
        MyLoader::class => MyLoaderLoaderFactory::class,
    ],
  ],
];
```

However the plugin manager configuration *does nothing*.

Debugging the code reveals that a `TranslatorPluginManager` will be created (with my factory set) in `Zend\I18n\Module->init()` via the ServiceListener.

The factory `Zend\Mvc\I18n\TranslatorFactory` is supposed to give the created PluginManager to the translator instance. But the factory only does that if the (main) DI-Container does not have a registered `Zend\I18n\Translator\TranslatorInterface`. But `Zend\I18n` registers a factory for this key and so a new PluginManager will be created and all my options are forgotten.

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
See issue description in https://github.com/zendframework/zend-mvc-i18n/issues/15

### CODE REVIEW

**Comment by weierophinney** [comment]
When reviewing this, my first take was: the factory for your own translation adapter should likely take care of injecting the plugin manager itself. The rationale is because `Zend\I18n\Translator\TranslatorInterface` _does not define the `setPluginManager()` method_. As such, we cannot assume that it is plugin-manager aware, and calling that method could raise errors for implementations where it is not present (e.g., mapping the TranslatorInterface to a factory producing a `DummyTranslator` instance).

I'd argue instead that you should have the factory for your own implementation pull the `TranslatorPluginManager` service and inject it:

```php
class MyLoaderFactory
{
    public function __invoke(ContainerInterface $container)
    {
        // ... create $translator ...
        $translator->setPluginManager($container->get('TranslatorPluginManager'));
        return $translator;
    }
}
```

(Alternately, inject the plugin manager via a delegator factory on your own service.)

**Comment by MatthiasKuehneEllerhold** [comment]
Sorry I dont understand what you're saying.

I thought that in order to register a custom loader I'd have to add its DI-Key to the "remote_translation"  and provide the plugin manager with a way to create it. This does **not** work, because the translator uses an empty `TranslatorPluginManager`. 

This error occurs on default configurations without a custom Translator-factory or anything else of the matter. Take a standard install (zend-mvc-i18n) and add this translator-config:
```php
return [
  'translator' => [
    'remote_translation' => [
        ['type' => MyLoader::class],
    ],
  ],
  'translator_plugins' => [
    'factories' => [
        MyLoader::class => MyLoaderLoaderFactory::class,
    ],
  ],
];
```

So no, my loader-factory wont be called and cant inject the PluginManager into the translator.

Or am I doing something wrong? If the use of a delegator is necessary for each remote loader than why is there a plugin manager at all?

**Comment by MatthiasKuehneEllerhold** [comment]
@weierophinney Is there a chance you'd reconsider this?

**Comment by weierophinney** [comment]
@MatthiasKuehneEllerhold — my apologies; I somehow mistook the remote loader for an alternate translation adapter.

You are definitely using correct configuration in your example from above (which included both the `translator.remote_translation` and `translator_plugins` keys). 

However, in looking through the `TranslatorServiceFactory` of zend-i18n, it does not inject the remote loader plugin manager (the service `TranslatorPluginManager`) into the generated translator instance. That is the root of the problem. Since that service, and the root translator service that requires it, are defined in the zend-i18n package, that's the more appropriate place to make the change. If you would be so kind as to make a PR against that package, I'll gladly review, merge, and release. Ping me via this issue once you do.

Thanks!

**Comment by MatthiasKuehneEllerhold** [comment]
I had the feeling that the plugin manager was part of `zend-mvc-i18n` (instead of `zend-i18n`). But you're right! I've opened the PR against `zend-i18n`!

**Pull request closed without merging**
